### ISSUE TITLE
Example of a ReactiveFormsGenerator on ViewModel

### ISSUE THREAD

**Issue by markbulingit** [artflutter/reactive_forms_generator#93]
I have this form class (generated by ReactiveFormsGenerator) called ReactiveProductForm,

can you please provide an example where ReactiveProductForm is placed on ViewModel and being called on View?

I already check the docs, particulary the
add_dynamic_controls_sample.dart

but it only shows generic reactive form :(

It would be very helpful if you can provide an example, Thanks!

**Comment by BenjiFarquhar** [comment]
@markbulingit Have a look at [this example](https://github.com/artflutter/reactive_forms_generator/issues/81#issuecomment-1411449965). The `EmailWidget` is the view, and the `EmailLogic` is actually a ViewModel, it is just named differently to relate to that specific question. It makes sense to only put the `FormModel` into the ViewModel because it is the actual state of the form, and the `ReactiveProductForm` is a widget, which I would say belongs in the view.
